name: CI Pipeline - Tests Only

on:
  push:
    branches:
      - '**'
      - '!develop'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for tests
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        env:
          MONGODB_HOST: localhost
          MONGODB_PORT: 27017
          MONGODB_DATABASE: dev
          MONGODB_USER: root
          MONGODB_PASSWORD: dev
          MONGO_URI: mongodb://root:dev@localhost:27017/dev
        run: npm run test

      - name: Run e2e tests
        env:
          MONGODB_HOST: localhost
          MONGODB_PORT: 27017
          MONGODB_DATABASE: dev
          MONGODB_USER: root
          MONGODB_PASSWORD: dev
          MONGO_URI: mongodb://root:dev@localhost:27017/dev
        run: npm run test:e2e
